### ISSUE TITLE
[Front] - Document Version

### ISSUE THREAD

**Issue by The0Jan** [MiniaczQ/apsi#30]
- [ ] Zdefiniowanie ról obowiązujących w obrębie dokumentu: autor, kontroler, recenzent, odbierający, zatwierdzający
- [ ] Możliwość usuwania dokumentów jeżeli ma się odpowiednie uprawnienia
- [ ] Przypisywanie ról do użytkowników w ramach wersji dokumentów ( Jeden użytkownik może mieć przypisane kila ról w obrębie pojedyńczego dokumentu)
- [ ]  Przy tworzeniu nowej wersji należy określić jej numer. Wstępna konwencja nazewnictwa 
wersji zakładała schemat: wersja rodzica, kropka, numer dziecka (liczony od 1). Przykład: 
wersja pierwsza ma numer wersji “1”. Pierwsza modyfikacja tej wersji dostaje numer “1.1”. 
Alternatywna modyfikacja wersji “1” nosi numer “1.2”. Jeśli powstanie wersja na bazie “1.2”, 
będzie to “1.2.1”, itd. Obecnie schemat nowego numeru wersji jest pozostawiony użytkownikowi do wyboru. Dla 
wersji bazowe np. 1.2 nowa wersja może być wersją podrzędną (1.2.1), współrzędną (1.3) lub 
nadrzędną (2.0).

**Comment by MortonPL** [comment]
-1, this is a mega-issue that should be split into smaller ones (already on it)

**Comment by MortonPL** [comment]
Also, I'd like to see the source of this versioning convention, because to me it is conter-intuitive (why is 1.2 alternative to 1.1?).

**Comment by The0Jan** [comment]
True that. I will send you the source right away.
