### ISSUE TITLE
[Front] Version merging

### ISSUE THREAD

**Issue by MortonPL** [MiniaczQ/apsi#38]
- [x] Allow users to merge alternative document versions together to create a new version
- [x] Allow users to pick which version should be the base one (the content of which is automatically copied)
- [x] Allow users to manually edit the new version before accepting

**Comment by Dove6** [comment]
- Users can pick one parent version (no changes here, "Create New Document Version" button is used for this):  
  ![image](https://github.com/MiniaczQ/apsi/assets/24943032/c6698833-71a3-4599-a814-12ec7032efb7)
- Users can select which versions will be merged (in addition to the "main" parent version):  
  ![image](https://github.com/MiniaczQ/apsi/assets/24943032/f70f05bb-64e9-4f7c-9004-6a4b310b5dba)
- The content of the "main" parent version is put in the "Content" field for users to "edit" while creating the new version.
