### ISSUE TITLE
User documentation update

### ISSUE THREAD

**Issue by buczi** [MiniaczQ/apsi#65]
- [x] Don't treat a condition as a separate steps. Prepare alternative scenarios.

For example the following part of use case U-1:

> 2. Użytkownik wprowadza dane
> 3. Dane zostały wprowadzone prawidłowo

should be rewritten as:

> 2. Użytkownik wprowadza *prawidłowe* dane

and then an alternative scenario can be created:

> 2. Użytkownik wprowadza *nieprawidłowe* dane

- [x] Don't use passive form, clearly state the actor in each step.

For example the following part of use case U-1:

> 4. Użytkownik dostaje informacje o udanej rejestracji

should be rewritten as:

> 4. System powiadamia użytkownika o udanej rejestracji

- [x] Add missing steps.

For example the following statement in use case U-1 is invalid:

> 5. Użytkownik jest przekierowany na stronę logowania

as the user has to click on the "Login" button in the navigation bar to get redirected to the login page.

**Comment by Dove6** [comment]
Moved some parts of the task to #79 and #80.

**Comment by MiniaczQ** [comment]
I added more use cases, still missing alternate cases, especially:
- existing name conflict for document creation, version creation
- concurrency conflict for version content or state update

**Comment by MiniaczQ** [comment]
I added alternative scenarios for cases above
