### ISSUE TITLE
Validate incoming models

### ISSUE THREAD

**Issue by MiniaczQ** [MiniaczQ/apsi#74]
- [x] Add data validation crate
- [x] Determine which data requires validation
- [x] Add data validation methods and attributes
- [x] Add utility for validation
- [x] Return data errors in well defined format

**Comment by Dove6** [comment]
The format of version name needs to be validated:

```regex
\d+(.\d+)*
```

**Comment by MiniaczQ** [comment]
Correct regex:
`^\d+(\.\d+)*$`
